Traceback (most recent call last):
  File "/home/cbnoonan/src/python/env/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 224, in loadobj
    global_conf=global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 278, in _loadconfig
    return loader.get_context(object_type, name, global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 409, in get_context
    section)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 431, in _context_from_use
    object_type, name=use, global_conf=global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 361, in get_context
    global_conf=global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 248, in loadcontext
    global_conf=global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 285, in _loadegg
    return loader.get_context(object_type, name, global_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 561, in get_context
    object_type, name=name)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 587, in find_egg_entry_point
    possible.append((entry.load(), protocol, entry.name))
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/setuptools-0.6c9-py2.6.egg/pkg_resources.py", line 1913, in load
  File "/home/cbnoonan/src/python/job/tictactoe/config/middleware.py", line 11, in <module>
    from tictactoe.config.environment import load_environment
  File "/home/cbnoonan/src/python/job/tictactoe/config/environment.py", line 7, in <module>
    from sqlalchemy import engine_from_config
ImportError: No module named sqlalchemy
Traceback (most recent call last):
  File "/home/cbnoonan/src/python/env/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 225, in loadobj
    return context.create()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 110, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/util/fixtypeerror.py", line 57, in fix_call
    val = callable(*args, **kw)
  File "/home/cbnoonan/src/python/job/tictactoe/config/middleware.py", line 37, in make_app
    config = load_environment(global_conf, app_conf)
  File "/home/cbnoonan/src/python/job/tictactoe/config/environment.py", line 28, in load_environment
    config.init_app(global_conf, app_conf, package='tictactoe', paths=paths)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/configuration.py", line 295, in init_app
    conf.update(self.pop('environment_load', {}))
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/configuration.py", line 134, in __getattr__
    conf_dict = self.current_conf()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Paste-1.7.2-py2.6.egg/paste/config.py", line 76, in _current_obj
    "No configuration has been registered for this process "
AttributeError: No configuration has been registered for this process or thread
Traceback (most recent call last):
  File "/home/cbnoonan/src/python/env/bin/paster", line 8, in <module>
    load_entry_point('PasteScript==1.7.3', 'console_scripts', 'paster')()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 84, in run
    invoke(command, command_name, options, args[1:])
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 123, in invoke
    exit_code = runner.run(args)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/command.py", line 218, in run
    result = self.command()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 276, in command
    relative_to=base, global_conf=vars)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteScript-1.7.3-py2.6.egg/paste/script/serve.py", line 313, in loadapp
    **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 204, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 225, in loadobj
    return context.create()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 625, in create
    return self.object_type.invoke(self)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/loadwsgi.py", line 110, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/PasteDeploy-1.3.3-py2.6.egg/paste/deploy/util/fixtypeerror.py", line 57, in fix_call
    val = callable(*args, **kw)
  File "/home/cbnoonan/src/python/job/tictactoe/config/middleware.py", line 37, in make_app
    config = load_environment(global_conf, app_conf)
  File "/home/cbnoonan/src/python/job/tictactoe/config/environment.py", line 28, in load_environment
    config.init_app(global_conf, app_conf, package='tictactoe', paths=paths)
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/configuration.py", line 295, in init_app
    conf.update(self.pop('environment_load', {}))
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Pylons-0.9.7-py2.6.egg/pylons/configuration.py", line 134, in __getattr__
    conf_dict = self.current_conf()
  File "/home/cbnoonan/src/python/env/lib/python2.6/site-packages/Paste-1.7.2-py2.6.egg/paste/config.py", line 76, in _current_obj
    "No configuration has been registered for this process "
AttributeError: No configuration has been registered for this process or thread
